argo-cd:
  server:
    config:
      repositories: |
        - url: git@github.com:bootstrapper-demo-org/k8s-infra.git
          sshPrivateKeySecret:
            name: argocd-git-ssh-readonly-k8s-infra
            key: private-key
        - url: git@github.com:bootstrapper-demo-org/k8s-apps-stg.git
          sshPrivateKeySecret:
            name: argocd-git-ssh-readonly-k8s-apps-stg
            key: private-key
        - type: helm
          url: https://argoproj.github.io/argo-helm
          name: argo
        - type: helm
          url: https://kubernetes.github.io/ingress-nginx
          name: ingress-nginx
        - type: helm
          url: https://charts.bitnami.com/bitnami
          name: external-dns
    ingress:
      hosts:
        - argocd.todo.b-demo.org

    additionalApplications:
      - name: argocd
        namespace: default
        project: default
        source:
          repoURL: git@github.com:bootstrapper-demo-org/k8s-infra.git
          targetRevision: main
          path: argocd
          helm:
            valueFiles:
              - values-stg.yaml
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true

      - name: argocd-apps
        namespace: default
        project: default
        source:
          repoURL: git@github.com:bootstrapper-demo-org/k8s-apps-stg.git
          targetRevision: main
          path: apps
          directory:
            recurse: true
            jsonnet: {}
        destination:
          server: https://kubernetes.default.svc
          namespace: default
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
